[project]
name = "datapipeline"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "google-cloud-storage>=3.4.1",
    "ipykernel>=6.30.1",
    "pandas>=2.3.3",
    "requests>=2.32.5",
]
