# test 03
name: CI CD Pipeline (ML)
run-name: ${{ github.actor }} submitted a CI CD Action for ML Pipeline
on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  Run-Workflow:    
    if: contains(github.event.head_commit.message, '/run-')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Comment ${{ github.event.head_commit.message }}"
      - run: echo "Job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "Branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - id: 'auth'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
      - name: Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker # --quiet #authenticate to gcr
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Build Workflow Container 
        run: |-
          cd ${{ github.workspace }}/src/workflow/
          docker build -t consult-app-workflow -f Dockerfile .
      - name: Run Data Collector
        if: contains(github.event.head_commit.message, '/run-data-collector')
        run: |-
          docker run --rm --name consult-app-workflow \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v ${{ github.workspace }}/src/frontend:/frontend \
            -v ${{ github.workspace }}/src/llm-api:/llm-api \
            -v ${{ github.workspace }}/src/llm-finetuning:/llm-finetuning \
            -v ${{ github.workspace }}/src/datapipeline:/datapipeline \
            -v ${{ github.workspace }}/src/models:/models \
            --mount type=bind,source=$GOOGLE_APPLICATION_CREDENTIALS,target=/secrets/deployment.json \
            -e GOOGLE_APPLICATION_CREDENTIALS=/secrets/deployment.json \
            -e USE_GKE_GCLOUD_AUTH_PLUGIN=True \
            -e GCP_PROJECT=vm1-test-473912 \
            -e GCP_ZONE=us-central1-a \
            -e GCS_BUCKET_NAME=consult-app-ml-workflow-demo \
            -e GCS_SERVICE_ACCOUNT=deployment@vm1-test-473912.iam.gserviceaccount.com \
            -e GCP_REGION=us-central1 \
            -e GCS_PACKAGE_URI=gs://consult-app-trainer-code \
            -e PULUMI_BUCKET=vm1-test-473912-pulumi-state-bucket \
            consult-app-workflow python cli.py --data_collector
      - name: Run Data Processor
        if: contains(github.event.head_commit.message, '/run-data-processor')
        run: |-
          docker run --rm --name consult-app-workflow \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v ${{ github.workspace }}/src/frontend:/frontend \
            -v ${{ github.workspace }}/src/llm-api:/llm-api \
            -v ${{ github.workspace }}/src/llm-finetuning:/llm-finetuning \
            -v ${{ github.workspace }}/src/datapipeline:/datapipeline \
            -v ${{ github.workspace }}/src/models:/models \
            --mount type=bind,source=$GOOGLE_APPLICATION_CREDENTIALS,target=/secrets/deployment.json \
            -e GOOGLE_APPLICATION_CREDENTIALS=/secrets/deployment.json \
            -e USE_GKE_GCLOUD_AUTH_PLUGIN=True \
            -e GCP_PROJECT=vm1-test-473912 \
            -e GCP_ZONE=us-central1-a \
            -e GCS_BUCKET_NAME=consult-app-ml-workflow-demo \
            -e GCS_SERVICE_ACCOUNT=deployment@vm1-test-473912.iam.gserviceaccount.com \
            -e GCP_REGION=us-central1 \
            -e GCS_PACKAGE_URI=gs://consult-app-trainer-code \
            -e PULUMI_BUCKET=vm1-test-473912-pulumi-state-bucket \
            consult-app-workflow python cli.py --data_processor
      - name: Run ML Pipeline
        if: contains(github.event.head_commit.message, '/run-ml-pipeline')
        run: |-
          docker run --rm --name consult-app-workflow \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v ${{ github.workspace }}/src/frontend:/frontend \
            -v ${{ github.workspace }}/src/llm-api:/llm-api \
            -v ${{ github.workspace }}/src/llm-finetuning:/llm-finetuning \
            -v ${{ github.workspace }}/src/datapipeline:/datapipeline \
            -v ${{ github.workspace }}/src/models:/models \
            --mount type=bind,source=$GOOGLE_APPLICATION_CREDENTIALS,target=/secrets/deployment.json \
            -e GOOGLE_APPLICATION_CREDENTIALS=/secrets/deployment.json \
            -e USE_GKE_GCLOUD_AUTH_PLUGIN=True \
            -e GCP_PROJECT=vm1-test-473912 \
            -e GCP_ZONE=us-central1-a \
            -e GCS_BUCKET_NAME=consult-app-ml-workflow-demo \
            -e GCS_SERVICE_ACCOUNT=deployment@vm1-test-473912.iam.gserviceaccount.com \
            -e GCP_REGION=us-central1 \
            -e GCS_PACKAGE_URI=gs://consult-app-trainer-code \
            -e PULUMI_BUCKET=vm1-test-473912-pulumi-state-bucket \
            consult-app-workflow python cli.py --pipeline
      - run: echo "Job's status is ${{ job.status }}."

